#payara.agentic.llm.model=dev.langchain4j.model.openai.OpenAiChatModel
#payara.agentic.llm.openai.api-key=${OPENAI_API_KEY}
#payara.agentic.llm.provider=OPEN_AI
#payara.agentic.llm.model-name=gpt-5
#payara.agentic.llm.provider.location=https://api.openai.com

payara.agentic.llm.provider=OPEN_AI
payara.agentic.llm.model=gpt-5
payara.agentic.llm.open_ai.base-url=https://api.openai.com